services:
  travel-journey_app:
    container_name: travel-journey
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3006:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
